export const themeData = JSON.parse("{\"blog\":{\"roundAvatar\":true,\"avatar\":\"/avatar3.jfif\",\"medias\":{\"Email\":\"https://example.com\",\"GitHub\":\"https://example.com\",\"QQ\":\"https://example.com\",\"Wechat\":\"https://example.com\"}},\"encrypt\":{\"config\":{\"/demo/encrypt.html\":[\"$2a$10$xvCvl38iPOgAhUinmskM2OchLJ8DvcJQjvpBngVbGjUW6QajJwu1.\"]}},\"pure\":false,\"darkmode\":\"switch\",\"themeColor\":false,\"fullscreen\":false,\"locales\":{\"/\":{\"blog\":{\"description\":\"一个旅途行者\",\"intro\":\"/intro.html\"},\"repoDisplay\":true,\"navbarIcon\":true,\"navbarAutoHide\":\"mobile\",\"hideSiteNameonMobile\":true,\"sidebar\":{\"/\":[\"\",{\"text\":\"文章\",\"icon\":\"note\",\"prefix\":\"posts/\",\"children\":\"structure\",\"collapsible\":true}],\"/archive/\":[{\"text\":\"大数据组件\",\"icon\":\"note\",\"prefix\":\"bigdata-components/\",\"collapsible\":true,\"children\":[{\"text\":\"Hadoop\",\"icon\":\"emmet\",\"prefix\":\"Hadoop/\",\"collapsible\":true,\"children\":\"structure\"},{\"text\":\"Kafka\",\"icon\":\"emmet\",\"prefix\":\"Kafka/\",\"collapsible\":true,\"children\":\"structure\"}]},\"bigdata-components/\",\"编程语言\"]},\"sidebarIcon\":true,\"headerDepth\":2,\"lang\":\"zh-CN\",\"navbarLocales\":{\"langName\":\"简体中文\",\"selectLangAriaLabel\":\"选择语言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"写作日期\",\"origin\":\"原创\",\"views\":\"访问量\",\"category\":\"分类\",\"tag\":\"标签\",\"readingTime\":\"阅读时间\",\"words\":\"字数\",\"toc\":\"此页内容\",\"prev\":\"上一页\",\"next\":\"下一页\",\"lastUpdated\":\"上次编辑于\",\"contributors\":\"贡献者\",\"editLink\":\"在 GitHub 上编辑此页\"},\"blogLocales\":{\"article\":\"文章\",\"articleList\":\"文章列表\",\"category\":\"分类\",\"tag\":\"标签\",\"timeline\":\"时间轴\",\"timelineTitle\":\"昨日不在\",\"all\":\"全部\",\"intro\":\"个人介绍\",\"star\":\"收藏\",\"slides\":\"幻灯片\",\"encrypt\":\"加密\"},\"paginationLocales\":{\"prev\":\"上一页\",\"next\":\"下一页\",\"navigate\":\"跳转到\",\"action\":\"前往\",\"errorText\":\"请输入 1 到 $page 之前的页码！\"},\"outlookLocales\":{\"themeColor\":\"主题色\",\"darkmode\":\"外观\",\"fullscreen\":\"全屏\"},\"encryptLocales\":{\"iconLabel\":\"文章已加密\",\"placeholder\":\"输入密码\",\"remember\":\"记住密码\",\"errorHint\":\"请输入正确的密码\"},\"routeLocales\":{\"notFoundMsg\":[\"这里什么也没有\",\"我们是怎么来到这儿的？\",\"这 是 四 零 四 !\",\"看起来你访问了一个失效的链接\"],\"back\":\"返回上一页\",\"home\":\"带我回家\",\"openInNewWindow\":\"Open in new window\"},\"author\":{\"name\":\"ZLin\",\"url\":\"https://mrhope.site\"},\"logo\":\"/logo.svg\",\"docsDir\":\"docs\",\"pageInfo\":[\"Author\",\"Original\",\"Date\",\"Category\",\"Tag\",\"ReadingTime\"],\"navbar\":[\"/\",{\"text\":\"归档\",\"icon\":\"note\",\"link\":\"/archive/\"},{\"text\":\"博文\",\"icon\":\"edit\",\"prefix\":\"/article/\",\"children\":[]},{\"text\":\"生活\",\"icon\":\"result\",\"link\":\"/life/\"},{\"text\":\"旅程\",\"icon\":\"sitemap\",\"link\":\"/journey/\"},{\"text\":\"理财\",\"icon\":\"proxy\",\"link\":\"/finance/\"},{\"text\":\"友链\",\"icon\":\"proxy\",\"link\":\"/friend/\"}],\"footer\":\"默认页脚\",\"displayFooter\":true}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
